apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: voting-app
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: voting_app
  MYSQL_USER: voting_user
  MYSQL_PASSWORD: vote_pass